doc: add vulns fixed in recent security release
nodejs/security-wg pull request #881
Opened 2023-02-17 17:48 UTC by mhdawson

2023-02-17 17:51 UTC, mhdawson commented
@RafaelGSS can you look at the validator it seems to be complaning in a way that does not make sense to me.

2023-02-18 02:13 UTC, RafaelGSS requested changes
@mhdawson This should fix it: https://github.com/nodejs/security-wg/pull/882

However, you don't need to update the index.json file. We have an action that will perform this for you https://github.com/nodejs/security-wg/blob/main/.github/workflows/update-core-index.yml.

2023-02-18 02:13 UTC, RafaelGSS commented on vuln/core/107.json
> +  "cve": ["CVE-2023-24807"],
```suggestion
  "cve": ["CVE-2023-23920"],
```

2023-02-18 18:08 UTC, RafaelGSS commented
@mhdawson I will go ahead and fix it. Feel free to revert if needed.

2023-02-18 18:12 UTC, RafaelGSS approved these changes

2023-02-18 18:13 UTC, merged